config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:create, :new, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
  resources :foods, only: [:index, :show, :new, :edit,:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  put '/recipes/:id/toggle_privacy', to: 'recipes#toggle_privacy', as: 'toggle_recipe_privacy'
  put '/recipes/:id/toggle_shopping_tag', to: 'recipes#toggle_shopping_tag', as: 'toggle_shopping_tag'
  patch 'shopping_lists/toggle_shopping_tag', to: 'shopping_lists#toggle_shopping_tag', as: 'toggle_shopping_tag_all'
  # Defines the root path route ("/")
  root "foods#index"
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, :measurement_unit, :user_id, presence: true
  validates :price, :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  # load_and_authorize_resource

  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = current_user.foods.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_url, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
        # redirect_to foods_path
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
  <td>
    <%= food.name %>
  </td>

  <td>
    <%= food.measurement_unit %>
  </td>

  <td>
    $ <%= food.price %>
  </td>

  <td>
    <%= food.quantity %>
  </td>

app/views/foods/_form.html.erb
<%= form_with(model: food, url: foods_path) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
   <%= form.label :measurement_unit, style: "display: block" %>
   <%= form.select :measurement_unit, ['grams (g)', 'kilograms (kg)', 'pounds (lb)', 'ounces (oz)', 'litres (L)', 'millilitres (mL)'] %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/index.html.erb
<% if user_signed_in? %>
<section>

<div class="new-food-link"> 
<%= link_to "New food", new_food_path %>
</div>

<div id="foods">
<table>
<thead>
  <tr>
    <th>Name</th>
    <th>Measurement unit</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Action</th>
  </tr>
</thead>
<tbody>
  <% @foods.each do |food| %>
    <tr>
    <%= render food %>
    <td>
    <%= button_to "Delete", food, method: :delete %>
    </td>
    </tr>
  <% end %>
  </tbody>
  </table>
</div>

</section>
<% end %>

app/views/foods/new.html.erb
<section class="flex-center">

<div class="form">

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

</div>

</section>