config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:create, :new, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
  resources :foods, only: [:index, :show, :new, :edit,:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  put '/recipes/:id/toggle_privacy', to: 'recipes#toggle_privacy', as: 'toggle_recipe_privacy'
  put '/recipes/:id/toggle_shopping_tag', to: 'recipes#toggle_shopping_tag', as: 'toggle_shopping_tag'
  patch 'shopping_lists/toggle_shopping_tag', to: 'shopping_lists#toggle_shopping_tag', as: 'toggle_shopping_tag_all'
  # Defines the root path route ("/")
  root "foods#index"
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @recipes = current_user.recipes
    # Get the list of missing food items for all recipes with shopping_tag true
    @recipe_foods = RecipeFood.includes(:food, :recipe, :user)
      .where(recipes: { shopping_tag: true })

    # Calculate the total count and price of missing food items
    @total_missing_count = 0
    @total_missing_price = 0
    @missing_foods = []

    @recipe_foods.each do |recipe_food|
      missing_quantity = recipe_food.quantity - recipe_food.food.quantity
      next unless missing_quantity.positive?

      @missing_foods << recipe_food
      @total_missing_count += 1
      @total_missing_price += missing_quantity * recipe_food.food.price
    end

    @shopping_tags_present = Recipe.exists?(shopping_tag: true)
  end

  def toggle_shopping_tag
    if Recipe.where(shopping_tag: true).exists?
      Recipe.update_all(shopping_tag: false)
    else
      Recipe.update_all(shopping_tag: true)
    end

    redirect_to shopping_lists_path
  end
end

app/views/shopping_lists/index.html.erb
<% if user_signed_in? %>

<section class="shopping-list">

  <h1 class="flex-center">Shopping List</h1>

  <div class="header-details">
    <p>Amount of food items to buy: <%= @total_missing_count %> </p>
    <p>Total value of food: $<%= @total_missing_price %> </p>
  </div>

  <div class="">
    <table>
      <thead>
          <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Recipe Name</th>
          <th>Owner</th>
          </tr>
      </thead>
      <tbody>
      <%@missing_foods.each do |food_item|%>
        <tr>
          <td><%=food_item.food.name%></td>
          <td><%= food_item.quantity - food_item.food.quantity %> <%= food_item.food.measurement_unit%></td>
          <td>$ <%=food_item.food.price * (food_item.quantity - food_item.food.quantity) %></td>
          <td>$ <%= food_item.recipe.name %></td>
          <td>$ <%= food_item.user.name %></td>
        </tr>
      <%end%>
      </tbody>
    </table>
  </div>

  
  <% if can? :update, @recipe %>
  
  <div class="back-to-recipe">
  <%= button_to (@shopping_tags_present ? "Remove all from shopping list" : "Add all to shopping list"), toggle_shopping_tag_all_path, method: :patch, class: "update-recipe" %>

  </div>
  <% end %>
  
  <div class="back-to-recipe">
  <%= link_to "Back to recipes", recipes_path %>
  </div>

  </section>
<% end %>