config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout',
    password: 'secret', confirmation: 'verification',
    registration: 'register', edit: 'edit/profile'
  }, sign_out_via: [:get, :post]

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:create, :new, :destroy]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
  resources :foods, only: [:index, :show, :new, :edit,:create, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  put '/recipes/:id/toggle_privacy', to: 'recipes#toggle_privacy', as: 'toggle_recipe_privacy'
  put '/recipes/:id/toggle_shopping_tag', to: 'recipes#toggle_shopping_tag', as: 'toggle_shopping_tag'
  patch 'shopping_lists/toggle_shopping_tag', to: 'shopping_lists#toggle_shopping_tag', as: 'toggle_shopping_tag_all'
  # Defines the root path route ("/")
  root "foods#index"
end

app/views/layouts/_nav.html.erb
<ul class="nav-bar">
  <% if user_signed_in? %>
  <li class="nav-item">
    <h2>
      <%= "#{current_user.name}" %>
    </h2>
  </li>
  <% else %>
  <li class="nav-item">
    <h2>
    Recipe App
    </h2>
  </li>
  <% end %>

  </li>
  <li class="nav-item">
    <%= link_to 'Food List', foods_path, class: "nav-link" %> 
  </li>
  <li class="nav-item">
    <%= link_to 'Recipe List', recipes_path, class: "nav-link" %> 
  </li>
  <li class="nav-item">
    <%= link_to 'Public Recipe List', public_recipes_path, class: "nav-link" %> 
  <li class="nav-item">
    <%= link_to 'General Shopping List', shopping_lists_path, class: "nav-link" %> 
  </li>
  <% if user_signed_in? %>
    <li class="nav-item">
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </li>
    <% else %>
    <li class="nav-item">
      <%= link_to "Log in", new_session_path(resource_name), class: "nav-link" %>
    </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <p class="notice flex-center"><%= notice %></p>
    <p class="alert flex-center"><%= alert %></p>

    <main id = "main-section">
    <%= yield %>
    </main>

    <footer id = "footer">
         <p>Created by Ibrahim & Mancoba &copy; <%= Time.now.year %> </p>
    </footer>
  </body>
</html>